name = "rdaptastic-api"
main = "src/index.ts"
compatibility_date = "2024-12-13"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
TURNSTILE_SECRET = "0x4AAAAAAA2MrWHk722FV70j2zDi4mLe5_s"
POSTHOG_API_KEY = "phc_rOMznyIIFLaEP4bK98xCjQtHCuENkqovXMbONBQ8lus"
POSTHOG_HOST = "https://eu.i.posthog.com"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1